name: Build and Lint
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-D warnings"
  CARGO_TERM_COLOR: always
  CARGO_BUILD_TARGET: wasm32-unknown-unknown

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Rustfmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy

      - name: Build
        run: cargo build --workspace --exclude common
